### ISSUE TITLE
Building MySlither

### ISSUE THREAD

**Issue by dickbalaska** [Mat2095/MySlither#2]
I built MySlither / dev branch and had three issues.

1) Java-WebSocket-1.4.0 required changes to the MySlitherWebSocketClient
-import org.java_websocket.drafts.Draft_17;
+import org.java_websocket.drafts.Draft_6455;
-super(serverUri, new Draft_17(), HEADER);
+super(serverUri, new Draft_6455(), HEADER);

2) Java-WebSocket also required slf4j-api and slf4j-simple

3) I couldn't get darcula to work. Maybe there's a font not on my Ubuntu system?
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.bulenkov.iconloader.IconLoader.<clinit>(IconLoader.java:53)
	at com.bulenkov.darcula.DarculaLaf.getDefaults(DarculaLaf.java:97)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:583)
	at de.mat2095.my_slither.Main.main(Main.java:11)
Caused by: java.lang.NullPointerException
	at com.bulenkov.iconloader.util.UIUtil.initSystemFontData(UIUtil.java:254)
	at com.bulenkov.iconloader.util.JBUI.calculateScaleFactor(JBUI.java:47)
	at com.bulenkov.iconloader.util.JBUI.<clinit>(JBUI.java:33)
	... 5 more

After that, it looks really good!

**Comment by Mat2095** [comment]
Hm, I really should add a build-script. I was unsing an older version of Java-WebSocket, where also I had no slf4j dependencies.

There seems to be two issues with darcula:
- darcula generally doesn't work with Java 9+: https://github.com/bulenkov/Darcula/issues/41
- exception while launching on linux: https://github.com/bulenkov/Darcula/issues/29
I'll add the workaround for now.

**Comment by Mat2095** [comment]
In the mean time, this fork seems to fix some things (haven't tried it though):
https://github.com/Flame239/slitherio
It is a maven-project, seems to use a newer websocket-library and has the darcula workaround.

**Comment by dickbalaska** [comment]
I added a build.gradle so I could build/run an uberjar (vs. running in the memory hog eclipse)
https://github.com/dickbalaska/MySlither/blob/dev/build.gradle

**Comment by Mat2095** [comment]
I fixed these issues on master and updated to protocol version 11.

**Comment by dickbalaska** [comment]
Thank you for the darcula fix.  I'm going to stick to branch dev for now because EaterBot is my favorite feature. (I'm using it on my server.)
